apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Helpa.Input.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Helpa.Input.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Helpa.Input.Name }}
    spec:
      containers:
      - {{ toYaml .Helpa.Input.Container | indentRest 8 }}
        ports:
        - {{ toYaml .Helpa.Input.Port | indentRest 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Helpa.Input.Name }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Helpa.Input.Port.ContainerPort }}
    protocol: {{ .Helpa.Input.Port.Protocol }}
  selector:
    app: {{ .Helpa.Input.Name }}
